[tool.poetry]
name = "p3"
version = "0.1.0"
description = ""
authors = ["David Ruhe <d.ruhe@uva.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
