config = {
    "name": "fps",
    "project": "cnf",
    "entity": "druhe",
    "method": "grid",
    "deterministic": True,
    "device": "cuda",
    "command": [
        "python",
        "-u",
        "fps.py",
        "config/cfg_fps.py",
        "${args}",
    ],
    "seed": 0,
    "continue": None,
    "dataset": dict(
        name="random_points",
        num_points=3,
        return_basis=False,
        batch_size=128,
        num_workers=4,
        n_prefetch=4,
    ),
    "model": dict(name="fpsnet"),
    "optimizer": {"name": "adam", "lr": 1e-3},
    # "scheduler": {"max_steps": 100_000, "warmup_steps": 1000, "decay_steps": 30000},
    "scheduler": None,
    "fit": {"max_steps": 100_000, "print_interval": 32},
    "parameters": {"seed": {"values": [0]}},
    "cluster": dict(
        address="snellius",
        directory="/home/druhe58/rail1/src/cnf/",
        slurm="--partition=gpu --time=120:00:00 --gpus-per-node=1",
    ),
}
