config = {
    "name": "modelnet40stf_clf",
    "project": "cnf",
    "entity": "druhe",
    "method": "grid",
    "deterministic": True,
    "device": "cuda",
    "command": [
        "python",
        "-u",
        "modelnet40stf_clf.py",
        "config/cfg_modelnet40stf_clf.py",
        "${args}",
    ],
    "seed": 0,
    "continue": None,
    "dataset": dict(
        name="modelnet40stf_points",
        num_points=1024,
        batch_size=32,
        num_workers=4,
        n_prefetch=2,
    ),
    "model": dict(name="pointnetpp"),
    "optimizer": {"name": "adam", "lr": 1e-3},
    # "scheduler": {"max_steps": 100_000, "warmup_steps": 1000, "decay_steps": 30000},
    "scheduler": None,
    "fit": {"max_steps": 100_000, "print_interval": 32},
    "parameters": {"seed": {"values": [0]}},
    "cluster": dict(
        address="snellius",
        directory="/home/druhe58/rail1/src/cnf/",
        slurm="--partition=gpu --time=120:00:00 --gpus-per-node=1",
    ),
}
