config = {
    "name": "random_points_ae",
    "project": "cnf",
    "entity": "druhe",
    "method": "grid",
    "deterministic": True,
    "device": "cuda",
    "command": [
        "python",
        "-u",
        "random_points_ae.py",
        "config/random_points_ae.py",
        "${args}",
    ],
    "seed": 0,
    "continue": None,
    "dataset": {
        "name": "random_points",
        "batch_size": 1024,
        "num_points": 128,
        "return_basis": False,
    },
    "model": {"name": "random_points_ae"},
    "optimizer": {"name": "adam", "lr": 5e-4},
    # "scheduler": {"max_steps": 100_000, "warmup_steps": 1000, "decay_steps": 30000},
    "scheduler": None,
    "fit": {"max_steps": 100_000},
    "parameters": {"seed": {"values": [0]}},
}
